name: mana
description: Prioritaria mobile com flutter para android e ios.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  http:
  http_interceptor:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.4.2
  firebase_auth: 0.15.3
  firebase_database: ^3.0.7
  flutter_map: any
  flutter_map_marker_cluster: any
  latlong: ^0.6.1
  fancy_bottom_navigation: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  firebase_core: 0.4.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/image_01.png
    - assets/img/image_02.png
    - assets/img/logo.png
    - assets/img/home/arrow.png
    - assets/img/home/banner_1.png
    - assets/img/home/banner_2.png
    - assets/img/home/banner_3.png
    - assets/img/home/banner_4.png
    - assets/img/home/banner_5.png
    - assets/img/home/dj.png
    - assets/img/home/icon_1.png
    - assets/img/home/icon_2.png
    - assets/img/home/icon_3.png
    - assets/img/home/map.png
    - assets/img/home/recent.png
    - assets/img/home/search.png
    - assets/img/home/avatar.png
    - assets/img/home/lable.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
